name: Setup ECR Private Auth
description: "Sets up Go and ECR Auth to build and push images"

inputs:
  AWS_GITHUB_RUNNER_ACCESS_KEY:
    description: "AWS Access Key of Github Runner user"
    required: true
  AWS_GITHUB_RUNNER_SECRET_KEY:
    description: "AWS Secret Key of Github Runner user"
    required: true
  GITHUB_PERSONAL_ACCESS_TOKEN:
    description: "Github Personal Access Token to use when pulling private go modules"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache: true
      env:
        GOPRIVATE: "github.com/ksoc-private"
        
    - name: Configure git for private modules
      shell: bash
      env:
        TOKEN: ${{ inputs.GITHUB_PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://ksocautomator:${TOKEN}@github.com".insteadOf "https://github.com"
      
    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_GITHUB_RUNNER_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_GITHUB_RUNNER_SECRET_KEY }}
