name: build-images-public

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      PUBLIC_GCR_JSON_KEY:
        required: true

permissions:
   contents: write # needed to write releases

jobs:
  build_image:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_JSON_KEY }}

      - name: Release Public GCR Image
        run: make build_image
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
          REGISTRY: us.gcr.io/ksoc-public
          BRANCH: ${{ github.base_ref }}
          COMMIT: ${{ github.sha }}

      - name: "Create release"
        if: startsWith(github.ref , 'refs/tags/v') == true
        uses: "ergebnis/.github/actions/github/release/create@1.9.0"
        with:
          github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
