name: build-images-public

on:
  workflow_call:
    inputs:
      service_name:
        required: false
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      PUBLIC_GCR_JSON_KEY:
        required: true

permissions:
   contents: write # needed to write releases

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect Version for Docker
        id: docker-version
        run: echo "VERSION=$(SEP="-" scripts/version)" >> $GITHUB_OUTPUT
      - name: Detect Version
        id: version
        run: echo "VERSION=$(scripts/version)" >> $GITHUB_OUTPUT
    outputs:
      docker-version: ${{ steps.docker-version.outputs.VERSION }}
      version: ${{ steps.version.outputs.VERSION }}

  build_image:
    runs-on: ubuntu-latest
    needs:
      - version
    env:
      SUMMARY: ${{ needs.version.outputs.docker-version }}
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_JSON_KEY }}

      - name: Release Public GCR Image
        run: make build_image
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CURRENT_TAG: ${{ needs.version.outputs.docker-version }}
          DOCKER_REGISTRY: us.gcr.io
          BRANCH: ${{ github.base_ref }}
          COMMIT: ${{ github.sha }}
          VERSION: ${{ needs.version.outputs.version }}

      # Ref: https://github.com/convictional/trigger-workflow-and-wait
      - name: Update api-client-ts
        if: startsWith(github.ref , 'refs/tags/v') == true
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ksoc-private
          repo: api-client-ts
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: draft-release.yml
          wait_workflow: false
