name: golangci-lint

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
    inputs:
      cache-sum-files:
        description: 'Glob pattern to go.sum files in the repo, for multi-module repos'
        default: 'go.sum'
        required: false
        type: string
      timeout:
        description: 'timeout for lint action, default is 5m'
        default: '5m'
        required: false
        type: string

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true # https://github.com/actions/setup-go#check-latest-version
          cache: true # https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
          cache-dependency-path: ${{ inputs.cache-sum-files }}
        env:
          GOPRIVATE: "github.com/ksoc-private"
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://ksocautomator:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.64
          args: --timeout=${{ inputs.timeout }}
