name: release

on:
  push:
    tags:
      - "v*"
  pull_request:

permissions:
  contents: write

jobs:
  release:
    uses: ksoc-private/go-github-actions/.github/workflows/release.yml@main
    with:
      is-public-image: false
    secrets: inherit
