name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect Version for Docker
        id: docker-version
        run: echo ::set-output name=VERSION::$(SEP="-" scripts/version)
      - name: Detect Version
        id: version
        run: echo ::set-output name=VERSION::$(scripts/version)
    outputs:
      docker-version: ${{ steps.docker-version.outputs.VERSION }}
      version: ${{ steps.version.outputs.VERSION }}

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - version
    env:
      SUMMARY: ${{ needs.version.outputs.docker-version }}
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true # https://github.com/actions/setup-go#check-latest-version
          cache: true # https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
        env:
          GOPRIVATE: "github.com/ksoc-private"

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://ksocautomator:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.PRIVATE_GCR_JSON_KEY }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          install-only: true

      - name: Release
        if: startsWith(github.ref , 'refs/tags/v') == true
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Snapshot
        if: startsWith(github.ref , 'refs/tags/v') == false
        run: make snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ needs.version.outputs.docker-version }}

      - name: Push Snapshot Docker Image
        if: startsWith(github.ref , 'refs/tags/v') == false
        run: |
          make docker_push_all
